# Generated by Django 2.2 on 2019-04-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('address', models.TextField(verbose_name='Dirección')),
            ],
        ),
    ]
