# Generated by Django 2.2 on 2019-04-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('folio', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Folio')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sex', models.CharField(max_length=10, verbose_name='Sexo')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('date_rescue', models.DateField(verbose_name='Fecha de rescate')),
            ],
        ),
    ]
